# ===============================
# PORT
# ===============================
server:
  port: 9020
  error:
    include-message: always
    include-binding-errors: always

# ===============================
# DATASOURCE
# ===============================

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_customer_store_online
    username: root
    password: romero123

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
